language: ruby
sudo: false
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install:
  - gem update --system
  - gem update bundler
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
matrix:
  allow_failures:
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.2.gemfile
